CREATE ROLE ddasoop LOGIN PASSWORD 'password'; -- 비밀번호 설정
CREATE ROLE migration LOGIN PASSWORD 'password'; -- 비밀번호 설정

GRANT CONNECT ON DATABASE ddasoop TO ddasoop;
GRANT CONNECT ON DATABASE ddasoop TO migration;

GRANT USAGE ON SCHEMA PUBLIC TO ddasoop;
GRANT USAGE, CREATE ON SCHEMA PUBLIC TO migration;

GRANT SELECT, INSERT, UPDATE, DELETE, ON ALL TABLES IN SCHEMA PUBLIC TO ddasoop;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA PUBLIC TO ddasoop;

ALTER DEFAULT PRIVILEGES FOR ROLE migration IN SCHEMA PUBLIC
      GRANT SELECT, INSERT, UPDATE, DELETE, ON TABLES TO ddasoop;

ALTER DEFAULT PRIVILEGES FOR ROLE migration IN SCHEMA PUBLIC
      GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ddasoop;